#!/usr/bin/env bash
#
# scripts
#
# set -euxo pipefail

# Debug log set Debug=true
DEBUG=false

# Globel base dir
BASE_DIR=$(dirname "$0")

# Import shell::utils::import
source ${BASE_DIR}/utils/import

# Import utils
shell::utils::import ${BASE_DIR}/utils

# Import mac and linux
shell::utils::import ${BASE_DIR}/mac/base
shell::utils::import ${BASE_DIR}/linux/base

# Usage
if [[ $# -eq 0 ]] || [[ $1 == '-h' ]]; then
    shell::utils::usage
    exit 1
fi

# main
case "$1" in
mac)
    ${DEBUG} && echo "mac script"
    shell::mac::base
    ;;
linux)
    ${DEBUG} && echo "linux script"
    shell::linux::base
    ;;
*)
    echo "other params!"
    shell::utils::usage
    ;;
esac
