#!/usr/bin/env bash
#
# scripts
#
# set -euxo pipefail

# debug log
DEBUG=false

# Globel base dir
BASE_DIR=$(dirname "$0")

# Import utils
for file in ${BASE_DIR}/utils/*; do
    ${DEBUG} && echo "import $(basename ${file})"
    source ${file}
done

# Import mac and linux
source ${BASE_DIR}/mac/base
source ${BASE_DIR}/linux/base

# Usage
if [[ $# -eq 0 ]]; then
    shell::utils::usage
    exit 1
fi

# main
case "$1" in
mac)
    ${DEBUG} && echo "mac script"
    shell::utils::mac
    ;;
linux)
    ${DEBUG} && echo "linux script"
    shell::utils::linux
    ;;
*)
    echo "other"
    ;;
esac
